# Generated by Django 5.2.8 on 2025-11-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BreachHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breach_name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='breaches.emailidentity')),
            ],
            options={
                'indexes': [models.Index(fields=['breach_name'], name='breaches_br_breach__08aff2_idx'), models.Index(fields=['identity', 'breach_name'], name='breaches_br_identit_9a721d_idx')],
            },
        ),
    ]
