# Generated by Django 5.2.8 on 2025-11-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breachhit',
            name='added_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='data_classes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_fabricated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_malware',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_retired',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_sensitive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_spam_list',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_stealer_log',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_subscription_free',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='logo_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='modified_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='pwn_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhit',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='breachhit',
            unique_together={('identity', 'breach_name')},
        ),
    ]
