# Generated by Django 5.2.8 on 2025-11-09 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaches', '0002_breachhit_added_on_breachhit_data_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShodanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('hostnames', models.JSONField(blank=True, default=list)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen', '-id'],
            },
        ),
    ]
