# Generated by Django 5.2.8 on 2025-11-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaches', '0003_shodanfinding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breachhit',
            options={'ordering': ['-occurred_on', '-added_on', '-id']},
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='data_classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_fabricated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_malware',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_spam_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_stealer_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_subscription_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='logo_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='pwn_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breachhit',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shodanfinding',
            name='org',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shodanfinding',
            name='os',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
